# Generated by Django 2.0.3 on 2018-03-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180319_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='manipulationcategory',
            name='display_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='display_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manipulationcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='expected_answer',
            field=models.CharField(choices=[('yes', 'tak'), ('no', 'nie')], max_length=32),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
