version: '2'
services:
  postgres:
    container_name: fzw-postgres
    image: postgres:10
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: fajniezewiesz
      POSTGRES_PASSWORD: fajniezewiesz
    volumes:
      - ./data/pg:/var/lib/postgresql/data
